# Change these first
owner: qik-meeting # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Qik Meeting App
    url: https://qik.mt

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://qik.mt/app/img/logo/favicon.svg
  name: Qik Meeting
  introTitle: "**Qik Meeting Status**"
  introMessage: Status & resolution updates for Qik Meeting App
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://qik.mt

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
